spring:
  application:
    name: prueba

  datasource:
    url: jdbc:mysql://localhost:9090/prueba2
    username: root
    password: jorgemcroa228#
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 6060
  servlet:
    context-path: /api/v1/prueba2 